// Concise, technically-accurate definitions for the VLAN jargon the lab
// surfaces. Wired as hover tooltips (native title=) and via the <Term> helper.

export const G: Record<string, string> = {
  VLAN: 'Virtual LAN — a broadcast domain defined in switch software. Ports assigned to the same VLAN behave as one isolated Layer-2 network; ports in different VLANs cannot reach each other without routing. Typically one VLAN maps 1:1 to an IP subnet.',
  'broadcast domain': 'The set of ports a broadcast frame (e.g. an ARP request) reaches. On a plain switch that is every port; each VLAN carves the switch into a separate broadcast domain.',
  'collision domain': 'A legacy half-duplex concept — the set of ports that could collide on a shared medium. Modern switched, full-duplex ports each form their own collision domain; VLANs are about broadcast domains, not collision domains.',
  '802.1Q': 'The IEEE standard for VLAN tagging on Ethernet. It inserts a 4-byte tag into the frame so a single trunk link can carry many VLANs while preserving which VLAN each frame belongs to.',
  'VLAN tag': 'The 4-byte 802.1Q field inserted after the source MAC and before the EtherType. It holds the TPID, PCP, DEI and the 12-bit VLAN ID. Present on trunks; stripped before a frame egresses an access port.',
  TPID: 'Tag Protocol Identifier — the first 2 bytes of the 802.1Q tag, value 0x8100, which flags the frame as VLAN-tagged (it sits where the EtherType would be, so 0x8100 tells the switch a tag follows).',
  PCP: 'Priority Code Point — 3 bits of the tag (0–7) carrying a Class of Service / 802.1p priority for QoS. Higher = more important.',
  'DEI/CFI': 'Drop Eligible Indicator (1 bit). Originally the Canonical Format Indicator (CFI) in the older spec; now marks a frame as drop-eligible under congestion.',
  'VLAN ID': 'The 12-bit VID in the 802.1Q tag identifying the VLAN. 12 bits → 4096 values; 0 and 4095 are reserved, leaving 4094 usable VLANs. VLAN 1 is the default.',
  '4094': '12 bits give 4096 VLAN IDs (0–4095). VLAN 0 (priority-only) and 4095 are reserved, so 4094 are usable. VLAN 1 is the default VLAN.',
  'access port': 'A switch port facing an end device. It belongs to exactly ONE VLAN, and frames to/from the host are ordinary UNTAGGED Ethernet — the host is unaware VLANs exist. The switch knows the VLAN from the port config.',
  'trunk port': 'A switch port that carries MANY VLANs between switches (or to a router/L3 device). Frames are 802.1Q-tagged so the far end knows each frame’s VLAN — except the native VLAN, which crosses untagged.',
  'tagged frame': 'An Ethernet frame carrying an 802.1Q tag — seen on trunk links so the receiver can tell which VLAN it belongs to.',
  'untagged frame': 'A plain Ethernet frame with no VLAN tag — what end hosts always send/receive on access ports, and what the native VLAN uses on a trunk.',
  'native VLAN': 'The one VLAN a trunk carries UNTAGGED (default VLAN 1). Any untagged frame arriving on a trunk is assumed to belong to the native VLAN. Both trunk ends must agree; a mismatch bridges two VLANs together.',
  'native mismatch': 'When the two ends of a trunk are configured with different native VLANs. Frames the sender leaves untagged (its native) are absorbed into the receiver’s different native VLAN — silently merging/leaking traffic between two VLANs.',
  'allowed-VLAN list': 'The set of VLANs a trunk is permitted to carry (“switchport trunk allowed vlan…”). Pruning a VLAN off the list stops its frames from crossing that trunk. A VLAN not in the list is dropped.',
  pruning: 'Removing VLANs from a trunk’s allowed list so their traffic (and broadcasts) don’t needlessly cross links where they aren’t used.',
  'default VLAN': 'VLAN 1 — every switch port starts here out of the box, and it is the default native VLAN on trunks. Best practice is to move access ports off VLAN 1 and use a dedicated, unused native VLAN.',
  'MAC table': 'The switch’s CAM/MAC-address table mapping learned MAC addresses to ports. It is scoped PER VLAN, so the same MAC could exist independently in two VLANs and lookups never cross VLAN boundaries.',
  'CAM table': 'Content-Addressable Memory table — the hardware MAC-address table a switch uses for fast per-VLAN MAC→port lookups.',
  ARP: 'Address Resolution Protocol — a host broadcasts “who has <IP>?” to learn the MAC for an IP in its own subnet/VLAN. The broadcast is confined to the sender’s VLAN.',
  broadcast: 'A frame addressed to ff:ff:ff:ff:ff:ff, flooded to every port in the same VLAN (and across trunks that carry it) — but never into another VLAN.',
  'inter-VLAN routing': 'Moving traffic between VLANs. Because VLANs are separate L2 domains (and subnets), a Layer-3 device (router or L3 switch) must route between them — switching alone cannot.',
  'router-on-a-stick': 'Inter-VLAN routing via a single physical router link configured as an 802.1Q trunk, with one SUBINTERFACE per VLAN (each holding that VLAN’s gateway IP). Cross-VLAN traffic hairpins up to the router and back down the same link — simple, but that link is a bottleneck.',
  subinterface: 'A logical interface (e.g. Gi0/0.10) on a router’s physical trunk link, tagged for one VLAN and holding that VLAN’s gateway IP. Router-on-a-stick uses one per VLAN.',
  SVI: 'Switched Virtual Interface — a virtual L3 interface on an L3 switch representing a VLAN (e.g. “interface vlan10”) and holding that VLAN’s gateway IP. The switch routes between SVIs in hardware — no hairpin, no external router.',
  'L3 switch': 'A switch that also routes in hardware. It runs an SVI per VLAN and forwards between VLANs at wire speed, replacing router-on-a-stick in modern designs.',
  'default gateway': 'The router/SVI IP a host sends packets to when the destination is in a different subnet/VLAN. Without a reachable gateway, a host can only talk within its own VLAN.',
  'IP subnet': 'A range of IP addresses (e.g. 10.0.1.0/24). In typical designs each VLAN maps to exactly one subnet, so “different VLAN” and “different subnet” go together and traffic between them must be routed.',
  DTP: 'Dynamic Trunking Protocol — a Cisco protocol that auto-negotiates whether a link becomes a trunk. Left enabled, an attacker can negotiate a trunk and reach every VLAN (switch-spoofing). Disable it: “switchport nonegotiate”.',
  'VLAN hopping': 'Attacks that let a host reach a VLAN it shouldn’t: switch-spoofing (negotiating a rogue trunk via DTP) and double-tagging (two stacked tags; the trunk’s native tag is stripped and the inner tag lands the frame in the victim VLAN).',
  'double tagging': 'A VLAN-hopping attack: the attacker sends a frame with two 802.1Q tags. The first switch strips the outer (native-VLAN) tag and forwards; the second switch reads the inner tag and delivers into the victim VLAN. One-way. Mitigated by a dedicated unused native VLAN.',
  'baby giant': 'An Ethernet frame slightly over the 1518-byte maximum because of the 4-byte 802.1Q tag (~1522 bytes). Switches must accept these on trunk links.',
  EtherType: 'The 2-byte field indicating the payload protocol (e.g. 0x0800 = IPv4). On a tagged frame it sits after the tag; the tag’s TPID (0x8100) occupies the original EtherType position.',
  FCS: 'Frame Check Sequence — the 4-byte CRC trailer that detects corruption. Adding/removing an 802.1Q tag forces the switch to recompute it.',
};
